services:
  - type: web
    name: kana-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false  # You'll set this manually in Render dashboard
      - key: CORE_API_KEY
        sync: false  # You'll set this manually in Render dashboard (if needed)
      - key: DATABASE_URL
        sync: false  # You'll set this manually in Render dashboard with your Supabase connection string
